FROM debian:12

ENV container=docker \
    DEBIAN_FRONTEND=noninteractive


RUN apt update \
 && apt install -y --no-install-recommends \
      systemd-sysv \
      curl \
      ca-certificates \
      sudo openssh-server curl lsb-release \
 && rm -rf /var/lib/apt/lists/*

RUN touch /tmp/disable_salt_checks \
 && curl -fsSL https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh \
    | sh -s -- -X stable \
 && rm -rf /var/cache/salt

RUN curl -fsSL https://raw.githubusercontent.com/saltstack/kitchen-salt/master/assets/install.sh \
    | sh

CMD ["/lib/systemd/systemd"]
